main: net.ingoh.minecraft.plugins.ingobotmc.Main
name: IngoBotMC
author: IngoH
softdepend: [Minecord]
version: 1.6.0
api-version: "1.20"
commands:
 i:
  description: All IngoBot commands
  permission: ingobotmc.i
  usage: /<command> <cmd> (args)
permissions:
 ingobotmc.*:
  description: All IngoBot permissions
  default: op
  children:
   ingobotmc.i:
    description: Permission for using the /i command.
    default: true