main: tv.ingoh.minecraft.plugins.ingobotcore.Main
name: IngoBotCore
author: IngoH
softdepend: [Minecord]
version: 1.2.5
api-version: 1.19
commands:
 i:
  description: All IngoBot commands
  permission: ingobotcore.i
  usage: /<command> <cmd> (args)
permissions:
 ingobotcore.*:
  description: All IngoBot permissions
  default: op
  children:
   ingobotcore.i:
    description: Permission for using the /i command.
    default: true